apiVersion: apps/v1
kind: Deployment
metadata:
  name: squid
  namespace: squid
  labels:
    name: squid
spec:
  replicas: 1
  selector:
    matchLabels:
      app: squid
  template:
    metadata:
      labels:
        app: squid
    spec:
      volumes:
        - name: squid-volume
          persistentVolumeClaim:
            claimName: squid-claim
        - name: squid-config-volume
          configMap:
            name: squid-configmap
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      containers:
        - name: squid
          image: squid:IMAGE_PLACEHOLDER
          imagePullPolicy: IfNotPresent
            #livenessProbe:
            #  httpGet:
            #    path: /healthz
            #    port: 5000
            #  initialDelaySeconds: 5
            #  periodSeconds: 60
            #  failureThreshold: 3
          resources:
            limits:
              memory: "4Gi"
          volumeMounts:
            - mountPath: /var/log/squid
              name: squid-volume
            - mountPath: /etc/squid-config # 指定configmap volume的目录
              name: squid-config-volume
